name: Push Container to Azure ContainerRegistry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }} # {mycontainer}.azurecr.io
      USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      IMAGE_NAME: sample-django-webapps
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker login ${REGISTRY_NAME} -u ${USERNAME} -p ${PASSWORD}
        docker build . -t ${REGISTRY_NAME}/${IMAGE_NAME}:${GITHUB_REF#refs/heads/}
        docker push ${REGISTRY_NAME}/${IMAGE_NAME}:${GITHUB_REF#refs/heads/}
